[default]
timeout = "600s"
jobs = 1
out = ["Html", "Lcov"]
output-dir = "target/tarpaulin"
exclude-files = ["fuzz/*", "tests/*"]
# Exclude test functions from coverage measurement
ignore-tests = true
