// SPDX-License-Identifier: MIT OR Apache-2.0
#![allow(dead_code, unused_imports)]

//! Fidelity reporting for dialect mapping.
//!
//! Provides `FidelityReport` generation that describes how faithfully a
//! conversation can be mapped from one dialect to another. Each feature
//! used in the request is classified by `FidelityLevel`.

use abp_core::ir::{IrContentBlock, IrConversation, IrRole};
use abp_dialect::Dialect;
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use crate::capabilities::{dialect_capabilities, Support};

// ── FidelityLevel ───────────────────────────────────────────────────────

/// Level of mapping fidelity for a field or concept.
///
/// Ordered from best to worst: `Lossless < Approximate < Degraded < Unsupported`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FidelityLevel {
    /// The mapping preserves all information with no loss.
    Lossless,
    /// Minor approximation but core semantics are preserved.
    Approximate,
    /// Significant information loss; some semantics change.
    Degraded,
    /// The feature cannot be represented in the target dialect.
    Unsupported,
}

impl std::fmt::Display for FidelityLevel {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Lossless => f.write_str("lossless"),
            Self::Approximate => f.write_str("approximate"),
            Self::Degraded => f.write_str("degraded"),
            Self::Unsupported => f.write_str("unsupported"),
        }
    }
}

// ── MappingEntry ────────────────────────────────────────────────────────

/// A single entry describing how one field or feature is mapped.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MappingEntry {
    /// Name of the field or feature being mapped.
    pub field_name: String,
    /// Type representation in the source dialect.
    pub source_value_type: String,
    /// Type representation in the target dialect.
    pub target_value_type: String,
    /// Fidelity level for this mapping.
    pub fidelity_level: FidelityLevel,
    /// Human-readable notes about the mapping.
    pub notes: String,
}

// ── FidelityReport ──────────────────────────────────────────────────────

/// Full fidelity report for a dialect mapping.
///
/// Generated by [`generate_fidelity_report`] to describe how faithfully
/// a specific request can be translated between two dialects.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FidelityReport {
    /// Dialect the request originates from.
    pub source_dialect: Dialect,
    /// Dialect the request is being mapped to.
    pub target_dialect: Dialect,
    /// Per-field mapping entries.
    pub entries: Vec<MappingEntry>,
    /// Overall fidelity (worst entry).
    pub overall_fidelity: FidelityLevel,
    /// When the report was generated.
    pub timestamp: DateTime<Utc>,
}

impl FidelityReport {
    /// Returns `true` when overall fidelity is [`FidelityLevel::Lossless`].
    #[must_use]
    pub fn is_lossless(&self) -> bool {
        self.overall_fidelity == FidelityLevel::Lossless
    }

    /// Returns entries at or worse than the given fidelity level.
    #[must_use]
    pub fn entries_at_level(&self, level: FidelityLevel) -> Vec<&MappingEntry> {
        self.entries
            .iter()
            .filter(|e| e.fidelity_level >= level)
            .collect()
    }

    /// Number of entries in the report.
    #[must_use]
    pub fn entry_count(&self) -> usize {
        self.entries.len()
    }
}

// ── generate_fidelity_report ────────────────────────────────────────────

/// Generate a fidelity report for mapping a request between dialects.
///
/// Analyzes the features used in `request` and compares source/target
/// dialect capabilities to produce per-field [`MappingEntry`] items.
#[must_use]
pub fn generate_fidelity_report(
    from_dialect: Dialect,
    to_dialect: Dialect,
    request: &IrConversation,
) -> FidelityReport {
    let from_caps = dialect_capabilities(from_dialect);
    let to_caps = dialect_capabilities(to_dialect);
    let mut entries = Vec::new();

    // Detect features used in the request
    let has_system = request.messages.iter().any(|m| m.role == IrRole::System);
    let has_thinking = request.messages.iter().any(|m| {
        m.content
            .iter()
            .any(|b| matches!(b, IrContentBlock::Thinking { .. }))
    });
    let has_images = request.messages.iter().any(|m| {
        m.content
            .iter()
            .any(|b| matches!(b, IrContentBlock::Image { .. }))
    });
    let has_tool_use = request.messages.iter().any(|m| {
        m.content
            .iter()
            .any(|b| matches!(b, IrContentBlock::ToolUse { .. }))
    });
    let has_tool_result = request.messages.iter().any(|m| {
        m.content
            .iter()
            .any(|b| matches!(b, IrContentBlock::ToolResult { .. }))
    });
    let has_text = request.messages.iter().any(|m| {
        m.content
            .iter()
            .any(|b| matches!(b, IrContentBlock::Text { .. }))
    });

    // Text — always lossless
    if has_text {
        entries.push(MappingEntry {
            field_name: "text_content".into(),
            source_value_type: "text".into(),
            target_value_type: "text".into(),
            fidelity_level: FidelityLevel::Lossless,
            notes: "Text content is universally supported".into(),
        });
    }

    // System prompt
    if has_system {
        let (level, target_type, notes) = if to_caps.system_prompt.is_native() {
            (
                FidelityLevel::Lossless,
                "system_message",
                "System prompt natively supported",
            )
        } else {
            (
                FidelityLevel::Degraded,
                "user_message",
                "System prompt converted to user message with [System] prefix",
            )
        };
        entries.push(MappingEntry {
            field_name: "system_prompt".into(),
            source_value_type: "system_message".into(),
            target_value_type: target_type.into(),
            fidelity_level: level,
            notes: notes.into(),
        });
    }

    // Thinking
    if has_thinking {
        let (level, target_type, notes) = if to_caps.thinking.is_native() {
            (
                FidelityLevel::Lossless,
                "thinking_block",
                "Thinking blocks natively supported",
            )
        } else {
            (
                FidelityLevel::Degraded,
                "text_block",
                "Thinking blocks degraded to text with [Thinking] prefix",
            )
        };
        entries.push(MappingEntry {
            field_name: "thinking".into(),
            source_value_type: "thinking_block".into(),
            target_value_type: target_type.into(),
            fidelity_level: level,
            notes: notes.into(),
        });
    }

    // Images
    if has_images {
        let (level, target_type, notes) = if to_caps.images.is_native() {
            (
                FidelityLevel::Lossless,
                "image_block",
                "Image content natively supported",
            )
        } else {
            (
                FidelityLevel::Unsupported,
                "text_placeholder",
                "Image content replaced with text placeholder",
            )
        };
        entries.push(MappingEntry {
            field_name: "images".into(),
            source_value_type: "image_block".into(),
            target_value_type: target_type.into(),
            fidelity_level: level,
            notes: notes.into(),
        });
    }

    // Tool use
    if has_tool_use || has_tool_result {
        let (level, target_type, notes) = if to_caps.tool_use.is_native() {
            if from_caps.tool_role == to_caps.tool_role {
                (
                    FidelityLevel::Lossless,
                    "tool_blocks",
                    "Tool use natively supported with same role model",
                )
            } else {
                (
                    FidelityLevel::Approximate,
                    "tool_blocks",
                    "Tool use supported but role representation differs",
                )
            }
        } else {
            (
                FidelityLevel::Unsupported,
                "unsupported",
                "Tool use not supported in target dialect",
            )
        };
        entries.push(MappingEntry {
            field_name: "tool_use".into(),
            source_value_type: "tool_blocks".into(),
            target_value_type: target_type.into(),
            fidelity_level: level,
            notes: notes.into(),
        });
    }

    // Overall fidelity = worst entry
    let overall_fidelity = entries
        .iter()
        .map(|e| e.fidelity_level)
        .max()
        .unwrap_or(FidelityLevel::Lossless);

    FidelityReport {
        source_dialect: from_dialect,
        target_dialect: to_dialect,
        entries,
        overall_fidelity,
        timestamp: Utc::now(),
    }
}

// ── Tests ───────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use abp_core::ir::IrMessage;
    use serde_json::json;

    // -- FidelityLevel --

    #[test]
    fn fidelity_level_ordering() {
        assert!(FidelityLevel::Lossless < FidelityLevel::Approximate);
        assert!(FidelityLevel::Approximate < FidelityLevel::Degraded);
        assert!(FidelityLevel::Degraded < FidelityLevel::Unsupported);
    }

    #[test]
    fn fidelity_level_display() {
        assert_eq!(FidelityLevel::Lossless.to_string(), "lossless");
        assert_eq!(FidelityLevel::Approximate.to_string(), "approximate");
        assert_eq!(FidelityLevel::Degraded.to_string(), "degraded");
        assert_eq!(FidelityLevel::Unsupported.to_string(), "unsupported");
    }

    #[test]
    fn fidelity_level_serde_roundtrip() {
        for level in [
            FidelityLevel::Lossless,
            FidelityLevel::Approximate,
            FidelityLevel::Degraded,
            FidelityLevel::Unsupported,
        ] {
            let json = serde_json::to_string(&level).unwrap();
            let back: FidelityLevel = serde_json::from_str(&json).unwrap();
            assert_eq!(back, level);
        }
    }

    // -- generate_fidelity_report --

    #[test]
    fn same_dialect_all_lossless() {
        let conv = IrConversation::from_messages(vec![
            IrMessage::text(IrRole::System, "sys"),
            IrMessage::text(IrRole::User, "hello"),
        ]);
        let report = generate_fidelity_report(Dialect::OpenAi, Dialect::OpenAi, &conv);
        assert!(report.is_lossless());
        assert_eq!(report.source_dialect, Dialect::OpenAi);
        assert_eq!(report.target_dialect, Dialect::OpenAi);
    }

    #[test]
    fn claude_to_openai_thinking_degraded() {
        let conv = IrConversation::from_messages(vec![
            IrMessage::text(IrRole::User, "solve"),
            IrMessage::new(
                IrRole::Assistant,
                vec![
                    IrContentBlock::Thinking { text: "hmm".into() },
                    IrContentBlock::Text { text: "42".into() },
                ],
            ),
        ]);
        let report = generate_fidelity_report(Dialect::Claude, Dialect::OpenAi, &conv);
        assert!(!report.is_lossless());
        let thinking = report
            .entries
            .iter()
            .find(|e| e.field_name == "thinking")
            .unwrap();
        assert_eq!(thinking.fidelity_level, FidelityLevel::Degraded);
    }

    #[test]
    fn claude_to_codex_many_unsupported() {
        let conv = IrConversation::from_messages(vec![
            IrMessage::text(IrRole::System, "sys"),
            IrMessage::new(
                IrRole::User,
                vec![IrContentBlock::Image {
                    media_type: "image/png".into(),
                    data: "data".into(),
                }],
            ),
            IrMessage::new(
                IrRole::Assistant,
                vec![IrContentBlock::ToolUse {
                    id: "t1".into(),
                    name: "test".into(),
                    input: json!({}),
                }],
            ),
        ]);
        let report = generate_fidelity_report(Dialect::Claude, Dialect::Codex, &conv);
        assert_eq!(report.overall_fidelity, FidelityLevel::Unsupported);
        let unsupported: Vec<_> = report
            .entries_at_level(FidelityLevel::Unsupported)
            .into_iter()
            .filter(|e| e.fidelity_level == FidelityLevel::Unsupported)
            .collect();
        assert!(unsupported.len() >= 2); // images + tools
    }

    #[test]
    fn overall_fidelity_is_worst_entry() {
        // Text (lossless) + thinking (degraded) → overall degraded
        let conv = IrConversation::from_messages(vec![IrMessage::new(
            IrRole::Assistant,
            vec![
                IrContentBlock::Text {
                    text: "answer".into(),
                },
                IrContentBlock::Thinking {
                    text: "think".into(),
                },
            ],
        )]);
        let report = generate_fidelity_report(Dialect::Claude, Dialect::OpenAi, &conv);
        assert_eq!(report.overall_fidelity, FidelityLevel::Degraded);
    }

    #[test]
    fn empty_request_lossless() {
        let conv = IrConversation::new();
        let report = generate_fidelity_report(Dialect::OpenAi, Dialect::Claude, &conv);
        assert!(report.is_lossless());
        assert_eq!(report.entry_count(), 0);
    }

    #[test]
    fn tool_use_openai_to_kimi_lossless() {
        // OpenAI → Kimi: both have tool_use + tool_role Native
        let conv = IrConversation::from_messages(vec![IrMessage::new(
            IrRole::Assistant,
            vec![IrContentBlock::ToolUse {
                id: "t1".into(),
                name: "test".into(),
                input: json!({}),
            }],
        )]);
        let report = generate_fidelity_report(Dialect::OpenAi, Dialect::Kimi, &conv);
        let tool_entry = report
            .entries
            .iter()
            .find(|e| e.field_name == "tool_use")
            .unwrap();
        assert_eq!(tool_entry.fidelity_level, FidelityLevel::Lossless);
    }

    #[test]
    fn tool_use_openai_to_claude_approximate() {
        // OpenAI (tool_role=Native) → Claude (tool_role=None) → Approximate
        let conv = IrConversation::from_messages(vec![IrMessage::new(
            IrRole::Assistant,
            vec![IrContentBlock::ToolUse {
                id: "t1".into(),
                name: "test".into(),
                input: json!({}),
            }],
        )]);
        let report = generate_fidelity_report(Dialect::OpenAi, Dialect::Claude, &conv);
        let tool_entry = report
            .entries
            .iter()
            .find(|e| e.field_name == "tool_use")
            .unwrap();
        assert_eq!(tool_entry.fidelity_level, FidelityLevel::Approximate);
    }

    #[test]
    fn images_openai_to_openai_lossless() {
        let conv = IrConversation::from_messages(vec![IrMessage::new(
            IrRole::User,
            vec![IrContentBlock::Image {
                media_type: "image/png".into(),
                data: "data".into(),
            }],
        )]);
        let report = generate_fidelity_report(Dialect::OpenAi, Dialect::OpenAi, &conv);
        let img = report
            .entries
            .iter()
            .find(|e| e.field_name == "images")
            .unwrap();
        assert_eq!(img.fidelity_level, FidelityLevel::Lossless);
    }

    #[test]
    fn images_openai_to_codex_unsupported() {
        let conv = IrConversation::from_messages(vec![IrMessage::new(
            IrRole::User,
            vec![IrContentBlock::Image {
                media_type: "image/png".into(),
                data: "data".into(),
            }],
        )]);
        let report = generate_fidelity_report(Dialect::OpenAi, Dialect::Codex, &conv);
        let img = report
            .entries
            .iter()
            .find(|e| e.field_name == "images")
            .unwrap();
        assert_eq!(img.fidelity_level, FidelityLevel::Unsupported);
    }

    #[test]
    fn report_serialize_roundtrip() {
        let conv = IrConversation::from_messages(vec![IrMessage::text(IrRole::User, "hi")]);
        let report = generate_fidelity_report(Dialect::OpenAi, Dialect::Claude, &conv);
        let json = serde_json::to_string(&report).unwrap();
        let back: FidelityReport = serde_json::from_str(&json).unwrap();
        assert_eq!(back.source_dialect, Dialect::OpenAi);
        assert_eq!(back.target_dialect, Dialect::Claude);
        assert_eq!(back.entry_count(), report.entry_count());
    }

    #[test]
    fn mapping_entry_serialize_roundtrip() {
        let entry = MappingEntry {
            field_name: "thinking".into(),
            source_value_type: "thinking_block".into(),
            target_value_type: "text_block".into(),
            fidelity_level: FidelityLevel::Degraded,
            notes: "degraded to text".into(),
        };
        let json = serde_json::to_string(&entry).unwrap();
        let back: MappingEntry = serde_json::from_str(&json).unwrap();
        assert_eq!(back.field_name, "thinking");
        assert_eq!(back.fidelity_level, FidelityLevel::Degraded);
    }

    #[test]
    fn entries_at_level_filters() {
        let conv = IrConversation::from_messages(vec![
            IrMessage::text(IrRole::System, "sys"),
            IrMessage::new(
                IrRole::User,
                vec![
                    IrContentBlock::Text {
                        text: "look".into(),
                    },
                    IrContentBlock::Image {
                        media_type: "image/png".into(),
                        data: "data".into(),
                    },
                ],
            ),
        ]);
        let report = generate_fidelity_report(Dialect::OpenAi, Dialect::Codex, &conv);
        let degraded_or_worse = report.entries_at_level(FidelityLevel::Degraded);
        assert!(!degraded_or_worse.is_empty());
        // All returned entries should be Degraded or worse
        for e in &degraded_or_worse {
            assert!(e.fidelity_level >= FidelityLevel::Degraded);
        }
    }

    #[test]
    fn all_dialect_pairs_produce_valid_report() {
        let conv = IrConversation::from_messages(vec![IrMessage::text(IrRole::User, "hello")]);
        for &from in Dialect::all() {
            for &to in Dialect::all() {
                let report = generate_fidelity_report(from, to, &conv);
                assert_eq!(report.source_dialect, from);
                assert_eq!(report.target_dialect, to);
                // Simple text should always be lossless
                assert!(report.is_lossless());
            }
        }
    }

    #[test]
    fn report_types_are_debug_clone() {
        let report =
            generate_fidelity_report(Dialect::OpenAi, Dialect::Claude, &IrConversation::new());
        let _ = format!("{:?}", report);
        let _ = report.clone();

        let entry = MappingEntry {
            field_name: "x".into(),
            source_value_type: "a".into(),
            target_value_type: "b".into(),
            fidelity_level: FidelityLevel::Lossless,
            notes: String::new(),
        };
        let _ = format!("{:?}", entry);
        let _ = entry.clone();
    }
}
